# Aquí lo que hay es una CONFIGURACIÓN WEB para que funcione PHP-FM ( PHP-FPM (FastCGI Process Manager) 
# es una alternativa de alto rendimiento a PHP FastCGI, diseñada para gestionar procesos PHP de manera 
# eficiente en servidores web, especialmente bajo tráfico intenso)
# Vamos, se responsabiliza en que el servidor web pueda procesar los archivos PHP dentro del contenedor.

server {
    # El querido nginx con su proxy inverso abre el puerto 80 dentro de los contenedores y por ahí le llegarán las peticiones.
    listen 80;
    listen [::]:80;
    # El _ escrito indica que se la sopla de qué dominio llega la petición.
    # Por eso en el proxy.conf se pone server_name nerevian.xyz; ;)
    server_name _;
    # Indica, importante eh!, que la web empieza en esa carpeta. 
    # Digo que es importante porque así la gente no se puede meter en otras carpetas que no sea esa.
    root /var/www/public;
 
    # Evita que otra página web pirata pueda meter tu web dentro de un <iframe> (ataques Clickjacking).
    add_header X-Frame-Options "SAMEORIGIN";
    # Obliga al navegador a respetar el tipo de archivo que le envías (evita que un hacker suba un .txt que en realidad sea un virus oculto).
    add_header X-Content-Type-Options "nosniff";
 
    # Le decimos que si alguien entra a la raíz de la web, busque el archivo index.php y que use texto estándar (utf-8).
    index index.php;
    charset utf-8;
 
    # TOP LINEA
    # Permite que nginx busque x archivo o carpeta y si no lo encuentra, lo mande a index.php
    # De esta forma Laravel puede gestionar las rutas.
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
 
    # Limpieza de logs para que no se llenen de errores 404.
    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }
 
    # Si no encuentra la página o carpeta o archivo x, manda al usuario en este caso a index.php pero puede ser cualquiera que se cree para que sea vea x página en vez de la default de nginx. 
    error_page 404 /index.php;
 
    # Aquí le decimos a nginx que cuando vea un archivo .php, se lo mande a PHP-FPM para que lo procese. 
    # fastcgi_pass 127.0.0.1:9000; le dice a nginx que se lo mande a PHP-FPM en el puerto 9000. 
    # fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name; le dice a PHP-FPM qué archivo tiene que procesar. 
    # include fastcgi_params; incluye los parámetros que necesita PHP-FPM para procesar el archivo. 
    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }
 
    # Prohibe el acceso a archivos ocultos (que empiezan con un punto) a menos que estén en la carpeta well-known.
    # Por ejemplo, no se puede acceder a .env, .htaccess, etc.
    location ~ /\.(?!well-known).* {
        deny all;
    }
}