server {
    listen 80; 
    # "Escucho todo lo que llegue por el puerto 80 (tráfico web estándar)".
    
    server_name nerevian.xyz; 
    # "Solo respondo si el usuario está buscando explícitamente este dominio".

    location / {
        # "Para cualquier ruta que me pidan (la barra '/' significa todo)..."

        proxy_pass http://laravel_app:80; 
        # LA LÍNEA MÁS IMPORTANTE. "Coge la petición, haz de puente y envíasela tal cual a la Máquina 2 (laravel_app) a su puerto 80".
        
        # CABECERAS (El chivatazo):
        # Como el proxy está haciendo de intermediario, Laravel se pensará que TODAS las visitas vienen de la IP del proxy. Estas líneas le pasan a Laravel los datos reales del usuario.
        proxy_set_header Host $host; 
        # "Dile a Laravel qué dominio pidió el usuario".
        proxy_set_header X-Real-IP $remote_addr; 
        # "Chívate a Laravel de cuál es la dirección IP real de la casa del usuario".
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
        # "Pasa el historial de proxies por los que ha pasado la petición".
        proxy_set_header X-Forwarded-Proto $scheme; 
        # "Dile a Laravel si el usuario entró por HTTP o HTTPS originalmente".
    }
}